apiVersion: apps/v1
kind: Deployment
metadata:
  name: warwebproject
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: warwebproject
          image: prema6396/devopsbasics:1.0.23
          ports:
            - containerPort: 80
