apiVersion: apps/v1
kind: Deployment
metadata:
  name: javagradleproject
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: javagradleproject
          image: graglecont.azurecr.io/prema6396/javanewproject:147
          ports:
           - containerPort: 80
      imagePullSecrets:
        - name: acr-repo-secret
     
